[tool.poetry]
name = "sqlalchemy learning"
version = "0.1.0"
description = ""
authors = ["Carlos Magno"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.36"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
